### PR TITLE
ContentBox Environment Refactor

### PR DESCRIPTION
**Pull request by jeff-chastain**
- Removed all local ContentBox files in favor of ContentBox Docker image (best practice)
- Reorganized local repository to include only custom files to be loaded and maintained
- Simplified installation / maintenance for local development

NOTE: The `/modules_app/solana` and `/modules_app/solanaApi` folders should NOT exist where they are.  I am not sure what their purpose is, but there should be no code outside of the defined ContentBox/ColdBox module structure noted @ https://contentbox.ortusbooks.com/back-end-development/back-end-development/modules

### CODE REVIEW

**Comment by hjozwiak** [comment]
I thought modules_app was the place to put things you wanted to have tracked in the source tree. Based on what I read from the docs, that is the right place for the solana modules.

**Comment by hjozwiak** [comment]
Okay; I spun a copy of the branch up on the computer here and I am getting a connection reset error in the browser and a database connection failure in the terminal. It tried to reconnect three times and gave up.

**Comment by hjozwiak** [comment]
@randalf11 can you checkout a copy and test it on your Mac?

**Comment by hjozwiak** [comment]
@jeff-chastain have you rebased recently? I'm getting this when I do a git status:
```
On branch docker-contentbox-updates
Your branch and 'staging' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	modules_app/contentbox-custom/_modules/Program/

nothing added to commit but untracked files present (use "git add" to track)
```
I will do more investigations into my database problems when I am more awake.

**Comment by hjozwiak** [comment]
Okay, I got it working on my box. There some weird pulling problems with mysql for some reason. Also, note well: if ou stop the database prematurely, MYSQL doesn't really appreciate that, so consider setting your timeout to a relatively high value so as to avoid this.

**Comment by mwilc0x** [comment]
I was able to pull this and install it locally to my Mac. I only had to change the .env.sample to .env.

One other question I have is where to place the Solana API? 

From our discussions, we wanted to have a way to manage user auth from the Vue app that could be used to authenticate against the Solana API as well. Is that something we can leverage with existing auth we get with ContentBox?

**Comment by jeff-chastain** [comment]
> I thought modules_app was the place to put things you wanted to have tracked in the source tree. Based on what I read from the docs, that is the right place for the solana modules.

@hjozwiak, the question is what is the code in SolanaAPI?  I did not dig into it.

Custom ColdBox modules go into the /modules_app folder.

For ContentBox, custom modules go into /modules_app/contentbox-custom/.

So the bottom line question is what is in the Solana and SolanaAPI folders?

**Comment by jeff-chastain** [comment]
> I was able to pull this and install it locally to my Mac. I only had to change the .env.sample to .env.
> 
> One other question I have is where to place the Solana API?
> 
> From our discussions, we wanted to have a way to manage user auth from the Vue app that could be used to authenticate against the Solana API as well. Is that something we can leverage with existing auth we get with ContentBox?

There should be no additional code necessary to have the VueJS app authenticate against the ContentBox API for user authentication.  That was built into the VueJS prototype I provided before.

When I was looking at the Solana API before, they did not have any concept of "authentication".  There was only the wallet token identifier.  So we need to dig further into what you want from a "Solana API Authentication" and whether that is possible.

**Comment by mwilc0x** [comment]
> > I was able to pull this and install it locally to my Mac. I only had to change the .env.sample to .env.
> > One other question I have is where to place the Solana API?
> > From our discussions, we wanted to have a way to manage user auth from the Vue app that could be used to authenticate against the Solana API as well. Is that something we can leverage with existing auth we get with ContentBox?
> 
> There should be no additional code necessary to have the VueJS app authenticate against the ContentBox API for user authentication. That was built into the VueJS prototype I provided before.
> 
> When I was looking at the Solana API before, they did not have any concept of "authentication". There was only the wallet token identifier. So we need to dig further into what you want from a "Solana API Authentication" and whether that is possible.

I think we just wanted a way to have JWT auth in front of some custom API routes.  For the Solana endpoints, if we were using a custom RPC node we would not want public to access those as it may drive up costs.

Also, and I don't know if this is not the normal way you would do it, but could the user authentication tie in to same user authentication from the ContentBox admin?

**Comment by hjozwiak** [comment]
The solana-api folder is a duplicate; it can be killed off post-merge. How do you configure the solana module such that the API routes become available?

**Comment by hjozwiak** [comment]
With respect to the authentication, there was a register endpoint in the docs but so far as I can tell has not been implemented. The idea was to use that to build a backing profile for a user who signs up with a Solana wallet.

**Comment by jeff-chastain** [comment]
> With respect to the authentication, there was a register endpoint in the docs but so far as I can tell has not been implemented. The idea was to use that to build a backing profile for a user who signs up with a Solana wallet.

@hjozwiak The ContentBox API supports user authentication with JWT tokens.  Check this out here:

https://s3.amazonaws.com/apidocs.ortussolutions.com/contentbox/5.3.0/apidoc.html#tag--Authentication

**Comment by mwilc0x** [comment]
> > With respect to the authentication, there was a register endpoint in the docs but so far as I can tell has not been implemented. The idea was to use that to build a backing profile for a user who signs up with a Solana wallet.
> 
> @hjozwiak The ContentBox API supports user authentication with JWT tokens. Check this out here:
> 
> https://s3.amazonaws.com/apidocs.ortussolutions.com/contentbox/5.3.0/apidoc.html#tag--Authentication

We wanted to know if we could register with this API and use that for the Vue registration, or if should be done another way.

**Comment by jeff-chastain** [comment]
> > > With respect to the authentication, there was a register endpoint in the docs but so far as I can tell has not been implemented. The idea was to use that to build a backing profile for a user who signs up with a Solana wallet.
> > 
> > 
> > @hjozwiak The ContentBox API supports user authentication with JWT tokens. Check this out here:
> > https://s3.amazonaws.com/apidocs.ortussolutions.com/contentbox/5.3.0/apidoc.html#tag--Authentication
> 
> We wanted to know if we could register with this API and use that for the Vue registration, or if should be done another way.

@mwilc0x, yes, the idea of users in ContentBox is represented as an "author".

https://s3.amazonaws.com/apidocs.ortussolutions.com/contentbox/5.3.0/apidoc.html#post-/cbapi/v1/authors

**Comment by mwilc0x** [comment]
> > > > With respect to the authentication, there was a register endpoint in the docs but so far as I can tell has not been implemented. The idea was to use that to build a backing profile for a user who signs up with a Solana wallet.
> > > 
> > > 
> > > @hjozwiak The ContentBox API supports user authentication with JWT tokens. Check this out here:
> > > https://s3.amazonaws.com/apidocs.ortussolutions.com/contentbox/5.3.0/apidoc.html#tag--Authentication
> > 
> > 
> > We wanted to know if we could register with this API and use that for the Vue registration, or if should be done another way.
> 
> @mwilc0x, yes, the idea of users in ContentBox is represented as an "author".
> 
> https://s3.amazonaws.com/apidocs.ortussolutions.com/contentbox/5.3.0/apidoc.html#post-/cbapi/v1/authors

We could not find a way to create an author with a password using the API. That is where we were not sure if should use another way to create new users.

I did not solve the new user using password with the other code I had. I did observe the Solana API module was only accessible with an auth token after using the `/login` when testing with Postman.

Our thinking was we maybe needed to extend the user authentication somehow for our use case.

I think our two main outstanding issues would be:

1. User authentication, specifically registering new user with password through API only.
2. Where we should configure the API routes in with this new file/folder structure.

**Comment by mwilc0x** [comment]
If this is something better to be asked on the Ortus discussion board let me know and I can ask there too.

**Pull request merged**
